In [2]:
import numpy as np

In [12]:
arr = np.zeros((100, 200))
arr = arr + 1

In [13]:
arr[0, :] = np.random.normal(size=200)

In [14]:
arr

array([[ 1.11508447, -0.99792082,  2.14304893, ...,  1.63403602,
         0.39110851,  0.54202757],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       ...,
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ]])

In [16]:
arr.mean(axis=0)

array([1.00115084, 0.98002079, 1.01143049, 0.98489106, 0.99800119,
       0.97440579, 0.97844718, 0.98762156, 0.97464537, 0.99593407,
       0.9943245 , 0.98225821, 1.01048448, 0.97710641, 0.97630291,
       0.98263494, 0.98497405, 0.98122771, 0.99707203, 0.98719232,
       0.99508133, 0.99303005, 1.00673815, 0.9921242 , 0.99855389,
       0.99673938, 0.99204394, 0.98633936, 0.98618803, 0.9816548 ,
       0.98443036, 0.98596583, 0.99533252, 0.9837852 , 0.99688672,
       1.01420048, 0.98694337, 0.99309695, 0.99560904, 0.99159802,
       0.98584734, 0.98355594, 0.99727351, 0.98096968, 0.98465399,
       0.99705446, 0.99479136, 0.99386027, 0.99301547, 0.9824603 ,
       0.99463907, 0.9825827 , 0.97804661, 0.97266958, 0.99244089,
       0.97839985, 0.98016332, 0.99371702, 0.97618084, 0.98708694,
       0.99794627, 0.99478801, 1.00309648, 0.98794841, 0.98099444,
       0.99594365, 1.0050704 , 0.99137128, 0.99498012, 0.96733158,
       0.99363824, 1.00292493, 0.99414631, 0.98504431, 0.99247

In [16]:
a = np.array([[1,1,1,1,0,0,0],[1,0,1,0,2,2,3], [1,2,4,5,6,7,4]])
b = np.array([[1,1,1,1,0,0,0],[1,0,1,0,2,1,2], [2,1,4,5,3,5,3]])

np.einsum('ij,ij->i', a, b) / (np.linalg.norm(a, axis=1)*np.linalg.norm(b, axis=1))

array([1.        , 0.96840025, 0.96169867])

In [9]:
np.tensordot(a, b)

IndexError: tuple index out of range